## Basic Operations
- /+ 
- /- 
- x - tf.matmul(), tf.tensordot(A, B, axis), usually set axis to 1
- /

All operations are spead up if using tf.<operation>

tf.transpose() and tf.reshape() will give different solutions, should user tf.transpose() usually

In [2]:
import tensorflow as tf

## Changing Data Types of tensors

- tf.cast(tensor, dtype=float32) or float16, decreasing size can lead to speed imporvements if not using a GPU or TPU, this is because the numbers will take up less space in memory

In [2]:
A = tf.constant([[10., 3.]], dtype=tf.float32)

A.dtype

tf.float32

In [4]:
B = tf.cast(A, dtype=tf.float16)
B.dtype

tf.float16

###  Aggregating Tensors:

Aggregating tensors = condensing them from multiple values to a smaller ammount of values through a pipeline of tasks

In [6]:
# Getting the absolute values of the tensors:

D = tf.constant([-7, -10])

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Usefull Aggregations:
- min
- max
- mean
- sum

In [3]:
# Creating a random tensor for practice:
import numpy as np

random_tensor = tf.constant(np.random.randint(0, 100, size=50))

In [9]:
random_tensor.shape

TensorShape([50])

In [11]:
# Finding Min:
tf.reduce_min(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [12]:
# Finding Max:
tf.reduce_max(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [13]:
# Mean:
tf.reduce_mean(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=50>

In [14]:
# Sum:
tf.reduce_sum(random_tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2507>

**Challenge** find the varience and the standard deviation of the tensor

In [18]:
# Standard deviation:
random_tensor = tf.cast(random_tensor, dtype=tf.float32) # Input needs to be a fload for it to be considered a "Real" or "Complex number"
tf.math.reduce_std(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=31.341352>

In [20]:
# Varience:
tf.math.reduce_variance(random_tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=982.2804>

### Finding positional min and max of a tensor:

In [24]:
# New tensor for finding positional min and max:

tf.random.set_seed(42)
A = tf.random.uniform([50])
A

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [25]:
# Positional (Arg) maths:

tf.argmax(A)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [28]:
# Index on our largest value:
A[tf.argmax(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [29]:
# Finding the max:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [30]:
# Finding the Min:
tf.argmin(A)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [31]:
# Min Value:
A[tf.argmin(A)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [32]:
# Confirming:
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing Tensors (Removing all 1D elements from the tensor)

In [33]:
# Creating Tensor:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [34]:
# Squeezing:
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

As can see, squeeze reduced away all the singular dimensions

### One Hot Encoding
- Very important for data cleaning
- Involves setting one element to '1' and the rest to '0', this creates the 1 hot encoding
- Inverse is 0 hot encoding

Is a form of numerical encoding

In [35]:
# Create a list of indicies

some_list = [0, 1, 2, 3] # Red, green blue or purple

# One hot encode: 

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Tensorflow and Numpy


In [4]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [5]:
# Tensor back to np:
np.array(J)

# Or:
J.numpy()

array([ 3.,  7., 10.])

In [7]:
# Defualt types of Numpy and TensorFlow are slightly different

numpy_J = tf.constant(np.array([3., 7., 10.])) # Float64
tensor_J = tf.constant([3., 7., 10.]) # Float32

numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Ensuring tensorflow runs well on GPU:

#### Finding Access to GPUs:
- Can test: `tf.config.list_physical_devices()`

#### If Using Google Colab can enable a free GPU:
- Notebook settings, then select a hardware accelerator
  - TPUs require more setup, GPUs are easy and free
- If you have acess to a CUDA-enabled GPU tensorflow will automatically use it whenever possible

In [9]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]